version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # OS
      - apt -y update
      - apt -y install graphviz fonts-ipafont plantuml
      # Python
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - sphinx-build -b html my_docs/source my_docs/build
artifacts:
  files:
    - "**/*"
  base-directory: "my_docs/build/"
  